kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  namespace: default
spec:
  type: NodePort
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - image: nginx
          ports:
            - containerPort: 80
              name: http
          name: nginx
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx-htpasswd
              name: htpasswd
            - mountPath: /etc/nginx
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: htpasswd
          configMap:
            name: nginx-htpasswd
        - name: config
          configMap:
            name: nginx-config
