apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-htpasswd
  namespace: default
data:
  htpasswd: |
    user1:$apr1$/woC1jnP$KAh0SsVn5qeSMjTtn0E9Q0
    sammy:$apr1$lzxsIfXG$tmCvCfb49vpPFwKGVsuYz.
