apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-htpasswd
  namespace: default
spec:
  encryptedData:
    htpasswd: AgCQFB3CVh67QgG3GsLnO81jJDL9qlEQw6FuuZfZyUbws8E4GPQx89NMZyezJJwqsfzQxGutMCOZQn48/QM1aZVUnUaCUnp/pK971cyJuB1/VEtg7BObFKiniV9hvccLAEm0KrlbeHdkiYYJldzjeoSLieMVF6iYcdcXKdMwkWyljqXqNDmePQJ9K21bj5ozPh4bEwSePcsAvI2RsgFu7a9NiZ7Kw18MBYk71qEQeRR2o7daH57KqQ6gYYoV0S97wghvKf+VuwtxkrmS7PPLP6XoBk/aqurIY7Kx7Yme8a9/gd1ee4s4Y9NVXUjNMey6KaubLeE4uIBlqtty1c5IwRQH7G1lutjwpAz13eSPButuXmXR5OqbAexcfN1twsLDhGEz8lDtVcI9BKyv6uqFo2C6/cyWo4J70RE09ouuKvBadkO4I1YUm2i2z7biVc+KoDOD+xJgAxBtavhVKERhHp4S2Za47ag1Sl47+ZxhBTHexmauvyvhU5XnNWeyuRS9A2majQJVw1yFARTs6u3AcFPvGWbsLKfvEDv4YNJSxuiY7Us8kDWD7HdFeFRqZrst8xpqBEuOIYm8w0GEn93GyyKph37cUEWqT3IRQu5fyAReBjs9JKrOGPaqI8hnGyXcFVX/JokT6XAjFjUyG5IIV4216Y3UOq+blkrrNznxvCFR+HZTXwEI0wM1PUG1B6E/2VJ4fBOMd/TLVhjWmjbHtEjam7ogpeTpXE6kKw78dR0Ai7I4u+IgCuA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nginx-htpasswd
      namespace: default

