apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-htpasswd
  namespace: default
spec:
  encryptedData:
    htpasswd: AgBBWKxSJZDg8ABGksMa6h5V0mAuZqMcV59CLdWvg3Z6wpxI/zu8vQS8pWouCPXLb2n9IVlTINTfB+k0OpmF3cD5//o21mqbZEDTeQExMS6EgwpUr4yqDe4n1SD9xvBhj3+q4NTwDZ0btJoJnR/oQuiEjzuZlfu20ho6jchIN1gqdq3I9U4PyVInn1zC2VjK89WnBj+T2DgokklYyKoGHaWRy0JeE1eU0DRQ8pvECC8BsjV3Ci1fbZEFG/jf/KGizfda8U5oVWHziiDVNuH3Fn1kj47h9vAqhryhwiviAiBgMe6aKf2er8rKAT1tiEwCqPIRlHeEP/m56I4so64nX2WNOySfft++WNaCi9KRhX9OfFwWfskByMV9HJnk78Ncr97LG7cR708eCpiOvrssZkYf9e0zeLS3Agg9A0y6nfpWngZuHGdogWhkgp7CoNn8X3gTx2N9zDPlyQ7OkNnuz/weUmUv5aZlStnknWFIc1EiNnMtHnjrKeT1jRaFcxiK+kFLqyUTQ0D9UhqOidMmIMnSFMEFuX7wmXmzfMphql+8c0uZ7cQOPqLwwA7A2u80iWrVailWz+Jnl+8Us/CcZzJSthNx/yIOdlTekc6/+vhgTIpL6yVFnqzzkEWWiwmEcO1lnP1XUUsObC+dl7KDY2W62812booVk45CPKy2Ru0/vNK77chRpOBhq8Tggk7bcRQo9lIDC+EWTXqwPFn0IbNCTEHxdJNM0rr1BLlY9LfKrcBtQ8EDhsG2AQuODl0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nginx-htpasswd
      namespace: default

