apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-htpasswd
  namespace: default
spec:
  encryptedData:
    htpasswd: AgB02N0aBlNyPk8/V6ADsRdx8ZsmNQgIyzkuoxHCP1kKCQm9ZAXdaYfwb/8pBmNthV6gyHzGFhd/sEL9JdCwe9YsIUdMK+DCYan42XbBg0/dMzqQ59M/5ztcJLWfORrrypqGnGssxku+bk5N4v6+j6ZJLU0jxtuoucExm4DUmAb41ck0Dg+FVS4rW0pXXgaTvdHYIRgzM76QvRrCNIHb5YmbSd+ixo7e6bQKxExUf1UdXe1gBLGSbzcaxLc00rlVvj4s+Ll6shYvBG3knE0ZTkcvOLLWLYOxMKSvIIwsPf2mTomMnKakvcSFlxDM069Q0wbV5AD4tgqUYDUeroTDN6oMtaNkU5aLoe7Qz0XRnazl3ckJOjdtJlk3flPbGqli35PukhRb/L5ihxhvKKkTsafT7rqOInW0mAluYeXwI8N0AAm5X8lQ00dzo658QBnxMeEAMsNqu6KriD12PVcboF6wJ8ABRRS7D/jWC8ND/BtVpRp4pIMzHtnXgfmXOSIXE9ncJwmK7P3LYxqFnSnWFgd4QXQl0ajABDm9NbpUgoTHDFUlL2nNN4OgVlanlnmxa9s578WpGuoAiN6LrYTdGiW+t6FiNUgSU74VHJBXjdTOPYitY6ZdHSkzqXdfgFGHtam8oZ2CE2EjRlHK73AEBPAEqzO41f4VMxTwwSrGq8jaBEKPV9zcDhOWPd3opmUkaQKouenttdX6dMe3MCNa7N/Y10QBWr+3/L+5f/Me/t0bNs+f9VyUrVV1itw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nginx-htpasswd
      namespace: default

