apiVersion: v1
kind: ConfigMap
metadata:
  name: htpasswd
  namespace: default
data:
  index.html: |
    <h1>Hello</h1>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  htpasswd: |
    user1:$apr1$/woC1jnP$KAh0SsVn5qeSMjTtn0E9Q0
    sammy:$apr1$lzxsIfXG$tmCvCfb49vpPFwKGVsuYz.
  nginx.conf: |
    events {}
    http {
      server {
        listen      80;
        server_name example.com;
        root        /usr/share/nginx/html;
        location / {
          auth_basic           "restricted";
          auth_basic_user_file htpasswd;
        }
      }
    }
